version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    volumes:
      - ./server:/server
    ports:
      - 8888:8888
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    volumes:
      - db_store:/var/lib/postgresql/data/
      - ./server/db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

volumes:
  db_store:

